KnowledgeGraph:
  enabled: true
  servers:
    - server: decider-genetic-kg
      address: deploy
      port: 7687
      description: "This knowledge graph contains information on Patients, Genes, SequenceVariants, CopyNumberAlterations, BiologicalPathways, and Drugs. It also contains relationships between these entities."

VectorStore:
  enabled: true
  servers:
    - server: local
      address: standalone
      port: 19530

OncoKBAPI:
  enabled: true
  description: "OncoKB API can query and fetch results from OncoKB. OncoKB is a precision oncology knowledge base and contains information about the effects and treatment implications of specific cancer gene alterations."

Text:
  Welcome:
    Title: Cancer Geneticist Assistant
    Disclaimer: |
      This is a use case demonstration, not a final product; it should not to be used in patient diagnosis or treatment. The data and information provided here are synthetic (in the case of patient data) or limited by demo access (in the case of the OncoKB API).
      ---
      For instance, the OncoKB API only returns full information of BRAF, TP53 and ROS1, but no other genes; and the patients in our dataset have names such as 'patient1' and randomised data attributes. For full access to the OncoKB API, an individual registration with OncoKB is necessary.
      ___
      *Please be aware that fundamental issues, such as the confabulation problem, cannot be solved by this tool, which is mainly a technical demonstration. LLM-generated content can be inaccurate and misleading.*
    About:
      Title: About
      Body1: |
        BioChatter is a tool to integrate biomedical research with current developments in Large Language Models in a user-friendly package. This pre-configured use case is its application to the complex problem of cancer genetics and treatment suggestion. The code for creating this tool is available on [GitHub](https://github.com/biocypher/decider-genetics); we also describe its creation in a [vignette](https://biochatter.org/vignettes/custom-decider-use-case) on our website. The conversational interface integrates information from various sources and facilitates their interpretation through natural language. The components are:
      ListItems1:
        - "Results from patient whole genome and RNA sequencing, yielding short variant calls, copy number alterations, and gene expression levels (synthetic data, available via KG)"
        - "External prior knowledge on genes and biological processes (real public data, available via KG)"
        - "External information on the clinical relevance of genetic alterations and approved/pipeline treatments (real public data, demo version limited to few genes, available via API)"
        - "Background knownledge of the ovarian cancer studied through semantic search in embeddings of relevant scientific literature (real public data, available via vector database RAG)"
      Heading2: How to use
      Body2: |
        The app is pre-configured with all input sources. You can ask the chat bot questions about the enriched patient data (KG), the biological background (vector DB), and clinical relevance / treatment suggestions for alterations (OncoKB API). For connecting to each of the resources, please select the corresponding checkbox in the lower right (RAG, KG RAG, or OncoKB). If one of the resources was used in the response, its results will be displayed in the contextual prompt widget (the rightmost button above the text input); the LLM is also instructed to comment on the external information. Here are some questions that you can ask; you can find more and copyable questions in the README of the [repository](https://github.com/biocypher/decider-genetics#questions):
      ListItems2:
        - (KG RAG) How many patients do we have on record, and what are their names?
        - (KG RAG) What was patient1's response to previous treatment, and which treatment did they receive?
        - (KG RAG) Which patients have hr deficiency but have not received parp inhibitors?
        - (KG RAG) Does patient4 have a sequence variant in a gene that is druggable? Which drug, and what evidence level has the association? Return unique values.
        - (OncoKB API) What is the consequence of the TP53 R273C mutation in high grade serous ovarian cancer?
        - (OncoKB API) Are there reports of of the functional fusion of CD47 and ROS1 in ovarian cancer?
        - (OncoKB API) What is the consequence of of the functional fusion of CD47 and ROS1?
        - (OncoKB API) What is the therapeutic relevance of the BRAF V600E mutation in high grade serous ovarian cancer?
        - (RAG) Have there been reports of TP53 being therapeutically relevant in HGSC?
        - (RAG) Do pro-inflammatory cytokines play a role in the progression of ovarian cancer?
        - (RAG) Does RAD51C play a role in ovarian cancer?
      Citation: "BioChatter is developed by a multicultural team over on [GitHub](https://github.com/biocypher) ([BioChatter](https://github.com/biocypher/biochatter), [BioChatter Server](https://github.com/biocypher/biochatter-server), [BioChatter Next](https://github.com/biocypher/biochatter-next), [BioChatter Light](https://github.com/biocypher/biochatter-light)), led by [Sebastian Lobentanzer](https://slobentanzer.github.io/). Biochatter Next was developed by Shaohong Feng and Cankun Wang, and is hosted by [BMBL](https://u.osu.edu/bmbl)."

  Masks:
    - name: Cancer Genetics Assistant
      avatar: "🧑<200d>🔬"
      context:
        - id: "cancer-genetics-assistant-1"
          role: "system"
          content: "You are an assistant to a cancer geneticist in the DECIDER consortium (https://deciderproject.eu)."
          date: ""
        - id: "cancer-genetics-assistant-2"
          role: "system"
          content: "Your role is to assist the user in the task of analysing patient data and prioritising treatments. You can retrieve auxiliary information from several tools (knowledge graph, vector database, API). If you receive input from these sources, include them in your responses, citing the source."
          date: ""
        - id: "cancer-genetics-assistant-3"
          role: "system"
          content: "You can receive additional information from multiple tools: A knowledge graph containing simulated patient information about their clinical history, somatic mutations and copy numbers of specific genes, the biological functions and druggability information of the affected genes; a searchable vector database with embeddings of relevant scientific literature on ovarian cancer; and a web API that can return information on cancer genes (only on BRAF, TP53 and ROS1) and treatment implications (OncoKB). The tools are used, one at a time, at the command of the user."
          date: ""
      modelConfig:
        model: gpt-3.5-turbo
        temperature: 0
        max_tokens: 2000
        presence_penalty: 0
        frequency_penalty: 0
        sendMemory: true
        historyMessageCount: 4
        compressMessageLengthThreshold: 2000
      lang: en
      builtin: true
      createdAt: 1697222692762
