# add your desired knowledge graph components here

patient:
    is_a: individual organism
    represented_as: node
    input_label: patient
    properties:
        id: str
        name: str

sample:
    synonym_for: material sample
    represented_as: node
    input_label: sample

gene:
    represented_as: node
    preferred_id: hgnc
    input_label: gene
    properties:
        chr: str
        start: int
        end: int
        strand: int
        band: str
        type: str
        name: str

drug:
    represented_as: node
    input_label: drug
    properties:
        id: str
        name: str

biological process:
    represented_as: node
    input_label: biological_process
    properties:
        id: str
        name: str

sequence variant:
    represented_as: node
    input_label: variant
    properties:
        CHROM: str
        POS: int
        REF: str
        ALT: str
        Gene.MANE: str
        CADD_phred: float
        AAChange.MANE: str
        COSMIC_TOTAL_OCC: str
        CLNSIG: str

patient to sample association:
    is_a: association
    represented_as: edge
    source: patient
    target: sample
    input_label: patient_has_sample

sample to variant association:
    is_a: association
    represented_as: edge
    source: sample
    target: sequence variant
    input_label: sample_has_variant

patient to variant association:
    is_a: association
    represented_as: edge
    source: patient
    target: sequence variant
    input_label: patient_has_variant

variant to gene association:
    is_a: association
    represented_as: edge
    source: sequence variant
    target: gene
    input_label: variant_in_gene

patient to gene copy number alteration:
    is_a: association
    represented_as: edge
    source: patient
    target: gene
    input_label: copy_number_alteration
    properties:
        nMajor: float
        nMinor: float
        purifiedLogR: float
        purifiedBaf: float
        purifiedLoh: float
        minPurifiedLogR: float
        maxPurifiedLogR: float
        breaksInGene: int

gene to biological process association:
    is_a: association
    represented_as: edge
    input_label: gene_to_process

gene druggability association:
    is_a: association
    represented_as: edge
    source: gene
    target: drug
    input_label: potentially_druggable
    properties:
        level: str
        alteration: str
        cancer_type: str
