# add your desired knowledge graph components here

patient:
    is_a: individual organism
    represented_as: node
    input_label: patient
    properties:
        id: str
        name: str
        age: int
        bmi: float
        stage: str
        treatment: str
        chemotherapy_cycles: int
        maintenance: str
        parpi: bool
        primary_outcome: str
        brca_mutation: bool
        hr_deficient: bool
        severe_adverse_reaction_to: str

gene:
    represented_as: node
    preferred_id: hgnc
    input_label: gene
    properties:
        chr: str
        start: int
        end: int
        strand: int
        band: str
        type: str
        name: str

drug:
    represented_as: node
    input_label: drug
    properties:
        id: str
        name: str

biological process:
    represented_as: node
    input_label: biological_process
    properties:
        id: str
        name: str

sequence variant:
    represented_as: node
    input_label: variant
    properties:
        CHROM: str
        POS: int
        REF: str
        ALT: str
        Gene.MANE: str
        CADD_phred: float
        AAChange.MANE: str
        COSMIC_TOTAL_OCC: str
        CLNSIG: str

copy number alteration:
    is_a: biological entity
    represented_as: node
    input_label: copy_number_variant
    properties:
        nMajor: float
        nMinor: float
        purifiedLogR: float
        purifiedBaf: float
        purifiedLoh: float
        minPurifiedLogR: float
        maxPurifiedLogR: float
        breaksInGene: int

patient to sequence variant association:
    is_a: association
    represented_as: edge
    source: patient
    target: sequence variant
    input_label: patient_has_variant

patient to copy number alteration association:
    is_a: association
    represented_as: edge
    source: patient
    target: copy number alteration
    input_label: patient_has_copy_number_variant

sequence variant to gene association:
    is_a: association
    represented_as: edge
    source: sequence variant
    target: gene
    input_label: variant_in_gene

copy number alteration to gene association:
    is_a: association
    represented_as: edge
    source: copy number alteration
    target: gene
    input_label: copy_number_variant_in_gene

gene to biological process association:
    is_a: association
    represented_as: edge
    input_label: gene_to_process
    source: gene
    target: biological process

gene druggability association:
    is_a: association
    represented_as: edge
    source: gene
    target: drug
    input_label: potentially_druggable
    properties:
        level: str
        alteration: str
        cancer_type: str
