# add your desired knowledge graph components here

patient:
    is_a: individual organism
    represented_as: node
    label_in_input: patient
    properties:
        id: str
        name: str

sample:
    synonym_for: material sample
    represented_as: node
    label_in_input: sample

gene:
    represented_as: node
    preferred_id: hgnc
    label_in_input: gene
    properties:
        chr: str
        start: int
        end: int
        strand: int
        band: str
        type: str
        name: str

biological process:
    represented_as: node
    label_in_input: biological_process
    properties:
        id: str
        name: str

sequence variant:
    represented_as: node
    label_in_input: variant
    properties:
        CHROM: str
        POS: int
        REF: str
        ALT: str
        Gene.MANE: str
        CADD_phred: float
        AAChange.MANE: str
        COSMIC_TOTAL_OCC: str
        CLNSIG: str

patient to sample association:
    is_a: association
    represented_as: edge
    label_in_input: patient_has_sample

sample to variant association:
    is_a: association
    represented_as: edge
    label_in_input: sample_has_variant

variant to gene association:
    is_a: association
    represented_as: edge
    label_in_input: variant_in_gene

sample to gene copy number alteration:
    is_a: association
    represented_as: edge
    label_in_input: copy_number_alteration

gene to biological process association:
    is_a: association
    represented_as: edge
    label_in_input: gene_to_process
