# add your desired knowledge graph components here

sequence variant:
    represented_as: node
    label_in_input: variant

patient:
    is_a: individual organism
    represented_as: node
    label_in_input: patient
    
patient to variant association:
    is_a: association
    represented_as: edge
    label_in_input: patient_has_variant
