# add your desired knowledge graph components here


patient:
    is_a: individual organism
    represented_as: node
    label_in_input: patient

sample:
    synonym_for: material sample
    represented_as: node
    label_in_input: sample

gene:
    represented_as: node
    label_in_input: gene

sequence variant:
    represented_as: node
    label_in_input: variant
    
patient to sample association:
    is_a: association
    represented_as: edge
    label_in_input: patient_has_sample

sample to variant association:
    is_a: association
    represented_as: edge
    label_in_input: sample_has_variant

sample to gene copy number alteration:
    is_a: association
    represented_as: edge
    label_in_input: copy_number_alteration
